// <auto-generated />
namespace ReleaseManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addreleasedata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addreleasedata));
        
        string IMigrationMetadata.Id
        {
            get { return "201909301246402_add-release-data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
