// <auto-generated />
namespace ReleaseManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addreleasefeaturestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addreleasefeaturestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201910232236368_add-release-features-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
